FROM python:3.11

# WORKDIR /usr/src/app
# install all dependencies
RUN pip install --upgrade pip
COPY requirements.txt ./
RUN pip install --no-cache-dir langchain openai python-dotenv chromadb orjson grpcio-tools tensorflow bs4 nltk sentence_transformers langchain_openai
# executer
# RUN pip3 install python-dotenv
# RUN pip3 install instructorembedding
COPY . .
RUN chmod +x entrypoint.sh
ENTRYPOINT [ "python server.py" ]