FROM python:3.11

# WORKDIR /usr/src/app
# install all dependencies
RUN pip install --upgrade pip
COPY . .
COPY requirements.txt ./
RUN python install.py
# executer
# RUN pip3 install python-dotenv
# RUN pip3 install instructorembedding
RUN chmod +x entrypoint.sh
CMD ["./entrypoint.sh"]